<a href="https://colab.research.google.com/github/m-majchrzak13/data-science-bootcamp/blob/main/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'2.0.2'

In [3]:
print(dir(np))

['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_core', '_distributor_init', '_expired_attrs_2_0', '_get_promotion_state', '_globals', '_int_extended_msg', '_mat', '_msg', '_no_nep50_warning', '_pyinstaller_hooks_dir', '_pytesttester', '_set_promotion_state', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_equiv', 'arra

In [4]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, 

In [5]:
x = np.array([1, 3])
x

array([1, 3])

In [6]:
print(x)

[1 3]


In [7]:
type(x)

numpy.ndarray

In [8]:
x.ndim

1

In [9]:
x.shape

(2,)

In [10]:
x.size

2

In [11]:
x.dtype

dtype('int64')

In [13]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [14]:
x.dtype

dtype('float64')

In [16]:
x = np.array([[1, 2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [17]:
x.ndim

2

In [18]:
x.shape

(2, 2)

In [19]:
x = np.array([[1, 2, 4], [4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [20]:
x.shape

(2, 3)

In [26]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],

    [[4, 1, 3],
    [4, 2, 1]],

     [[3, 2, 1],
      [4, 3, 2]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [27]:
x.ndim

3

In [28]:
x.shape

(3, 2, 3)

In [29]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [30]:
A = np.array([1.0, 2.3, 3.1])
A.dtype

dtype('float64')

In [31]:
A = np.array([1, 2, 3], dtype='float')
A.dtype

dtype('float64')

In [33]:
A = np.array([1, 2, 3], dtype='complex')
A.dtype

dtype('complex128')

In [35]:
A = np.array([1.0, 2.3, 3.1], dtype='int')
A.dtype

dtype('int64')

In [36]:
A

array([1, 2, 3])

In [37]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [39]:
A = np.array([24, 120, 230], dtype=np.uint8)
A.dtype

dtype('uint8')