<a href="https://colab.research.google.com/github/m-majchrzak13/data-science-bootcamp/blob/main/01_wprowadzenie/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.__version__

'2.0.2'

In [ ]:
v1 = np.array([-1, 4])
v1

array([-1,  4])

In [ ]:
np.linalg.norm(v1)

np.float64(4.123105625617661)

In [ ]:
v2 = np.array([-10, 10, 13])
v2

array([-10,  10,  13])

In [ ]:
np.linalg.norm(v2)

np.float64(19.209372712298546)

In [ ]:
p = np.array([3, 0])
q = np.array([0, 4])

np.linalg.norm(p - q)

np.float64(5.0)

In [ ]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])

np.linalg.norm(p - q)

np.float64(5.0990195135927845)

In [ ]:
X = np.array([[5, 3], [3, 9]])
Y = np.array([[1], [-1]])
print(X, '\n')
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [ ]:
z = np.dot(X, Y)
z

array([[ 2],
       [-6]])

In [ ]:
z.shape

(2, 1)

In [ ]:
X = np.array([[2, -1, 3],
              [3, 1, 0]])
Y = np.array([[2, 1, -1],
              [0, -1, 2],
              [3, 2, 0]])

print(X, '\n')
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [ ]:
np.dot(X, Y)

array([[13,  9, -4],
       [ 6,  2, -1]])

In [ ]:
A = np.array([[2, 4], [-1, 3]])
round(np.linalg.det(A))

10

In [ ]:
A = np.array([[2, 4], [-1, 3]])
np.trace(A)

np.int64(5)

In [ ]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
A

array([[ 2,  4],
       [-1,  3]])

In [ ]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [ ]:
np.set_printoptions(precision=4, suppress=True)

np.dot(A, B)

array([[1., 0.],
       [0., 1.]])

In [ ]:
np.dot(B, A)

array([[ 1., -0.],
       [ 0.,  1.]])

In [ ]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [ ]:
A.T

array([[ 2, -1],
       [ 4,  3]])

In [ ]:
A = np.array([[2, 4], [1, -1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [ ]:
B = np.array([[10], [-1]])
print(B)

[[10]
 [-1]]


In [ ]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])

In [ ]:
X.shape

(2, 1)